# Generated by Django 3.2.19 on 2023-06-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
                ('LicenseType', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeRate', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictName', models.CharField(max_length=45)),
                ('Coordination', models.CharField(max_length=45)),
                ('Population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonationTime', models.DateTimeField()),
                ('DonationDeliveryTime', models.DateTimeField()),
                ('RequestID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('Surname', models.CharField(max_length=225)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(max_length=45)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionCost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestTime', models.DateTimeField()),
                ('CurrentStatus', models.CharField(max_length=45)),
                ('DeliveryTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=45)),
                ('Phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleType', models.CharField(max_length=45)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('Surname', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
                ('PhoneNumber', models.CharField(max_length=45)),
                ('District_DistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='RequestVehiceCourrierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryTime', models.DateTimeField()),
                ('Courier_CourierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courier')),
                ('Request_RequesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
                ('Vehicle_VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHasLogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogisticsCompany_CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logisticscompany')),
                ('Request_RequesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHasItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Items_ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('Request_RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='Victim_RequesterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.victim'),
        ),
        migrations.CreateModel(
            name='PurchaseHasSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_PurchaseTransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase')),
                ('Supplier_SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHasItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('UnitItemCost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Items_ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('Purchase_PurchaseTransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCompanyHasDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostOfOutsource', models.DecimalField(decimal_places=2, max_digits=15)),
                ('District_DistrictID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('LogisticsCompany_CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logisticscompany')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHasItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Donation_DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.donation')),
                ('Items_ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHasCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency_CurrencyType', models.CharField(max_length=45)),
                ('Amount', models.IntegerField()),
                ('Donation_DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='Donator_DonatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.donator'),
        ),
        migrations.AddField(
            model_name='donation',
            name='Request_RequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request'),
        ),
    ]
