# Generated by Django 3.2.19 on 2023-06-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='RequestID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Request_RequestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.request'),
        ),
    ]
