# Generated by Django 3.2.19 on 2023-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230626_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='DeliveryTime',
            field=models.DateTimeField(null=True),
        ),
    ]
